image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables: 
  PROJECT_ID: "buoyant-imagery-424204-k9"
  IMAGE_NAME: "fastapi_project-fastapi"
  GCP_ZONE: "us-central1-f"
  GCP_INSTANCE_NAME: "instance-20240523-044228"
  GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY

before_script:
  - echo $GCLOUD_SERVICE_KEY | base64 -d > ${CI_PROJECT_DIR}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/gcloud-service-key.json
  - gcloud config set project $PROJECT_ID
  - gcloud auth configure-docker

build:
  stage: build
  script:
    - docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_SHA

deploy:
  stage: deploy
  script:
    - gcloud compute ssh $GCP_INSTANCE_NAME --zone $GCP_ZONE --command "docker pull gcr.io/$PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_SHA && docker-compose -f /home/oswin9089/docker-compose.yml up -d"
