version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mastertai0125
      MYSQL_DATABASE: JuboTest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+aiomysql://root:mastertai0125@mysql/JuboTest

volumes:
  mysql_data:
